org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
# Gradle requires JDK 17+. Point it to the installed JDK 17.
org.gradle.java.home=D:\\Environment\\java\\java17.0.18
# Disable Kotlin daemon/incremental caches to avoid "Could not close incremental caches" errors.
kotlin.compiler.execution.strategy=in-process
kotlin.incremental=false
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
